spring.application.name=apilogin

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# docker run -d -p 1025:1025 -p 8025:8025 mailhog/mailhog
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

# Token expira en 5 minutos para pruebas
application.security.jwt.expiration=300000
application.security.jwt.secret-key=ClaveAleatoria
# Refresh expira en 10 minutos para pruebas
application.security.jwt.refresh-token.expiration=600000
application.security.jwt.pretoken.expiration=600000